// data-full.js
// Danh sách hơn 100 nhân vật Tam Quốc với avatar, nhóm, tiểu sử và mối quan hệ

const nodes = [
  // Thục
  { id: "Lưu Bị", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Liu_Bei_Tang.jpg/250px-Liu_Bei_Tang.jpg", bio: "Hoàng đế khai quốc Thục Hán, nổi tiếng vì nhân nghĩa và tình huynh đệ với Quan Vũ và Trương Phi." },
  { id: "Quan Vũ", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Guanyu-1.jpg/250px-Guanyu-1.jpg", bio: "Danh tướng Thục Hán, được tôn sùng như Võ Thánh, là anh em kết nghĩa với Lưu Bị." },
  { id: "Trương Phi", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/ZhangFei.jpg/250px-ZhangFei.jpg", bio: "Một trong ba anh em kết nghĩa Lưu Quan Trương, nổi tiếng vì tính khí nóng nảy nhưng trung nghĩa." },
  { id: "Gia Cát Lượng", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/%E8%9C%80%E6%B1%89%E4%B8%9E%E7%9B%B8%E5%BF%A0%E6%AD%A6%E4%BE%AF%E8%AF%B8%E8%91%9B%E4%BA%AE.jpg/250px-%E8%9C%80%E6%B1%89%E4%B8%9E%E7%9B%B8%E5%BF%A0%E6%AD%A6%E4%BE%AF%E8%AF%B8%E8%91%9B%E4%BA%AE.jpg", bio: "Khổng Minh, thừa tướng Thục Hán, nhà chiến lược và quân sư thiên tài thời Tam Quốc." },
  { id: "Triệu Vân", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/b/be/Zhao_Yun_statue.jpg", bio: "Dũng tướng Thục Hán, nổi tiếng qua trận cứu A Đẩu tại Trường Bản." },
  { id: "Ngụy Diên", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/6/67/Wei_Yan_statue.jpg", bio: "Danh tướng Thục Hán, lập nhiều chiến công nhưng bị nghi kỵ và kết cục bi thảm." },
  { id: "Mã Siêu", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/f/f2/Ma_Chao_statue.jpg", bio: "Một trong Ngũ hổ tướng, từng chống Tào Tháo trước khi theo Lưu Bị." },
  { id: "Hoàng Trung", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/e/e1/Huang_Zhong_statue.jpg", bio: "Lão tướng Thục Hán, lừng danh với chiến công tại Định Quân Sơn." },
  { id: "Pháp Chính", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/FaZheng.jpg/250px-FaZheng.jpg", bio: "Khi Lưu Bị vào đất Thục, Pháp Chính về làm mưu thần cho Lưu Bị, được Bị rất tín nhiệm và kính trọng." },
  { id: "Bàng Thống", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Pang_Tong_portrait.jpg", bio: "Phượng Sồ, mưu sĩ tài năng của Lưu Bị, tử trận tại Lạc Phượng." },
  { id: "Hoàng Nguyệt Anh", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/7/74/Huang_Yueying.jpg", bio: "Vợ của Gia Cát Lượng, nổi tiếng thông minh và tài giỏi." },
  { id: "A Đẩu", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/0/06/Liu_Shan_portrait.jpg", bio: "Lưu Thiện, con trai Lưu Bị, hoàng đế thứ hai của Thục Hán." },
  { id: "Mã Đại", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Ma_Dai_statue.jpg", bio: "Cháu trai Mã Siêu, từng tham gia Bắc phạt cùng Gia Cát Lượng và giết Ngụy Diên." },
  { id: "Quan Bình", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/a/a3/Guan_Ping_statue.jpg", bio: "Nghĩa tử Quan Vũ, tử trận cùng cha tại Mã Thành." },
  { id: "Quan Hưng", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/3/38/Guan_Xing_statue.jpg", bio: "Con trai Quan Vũ, kế thừa chức vụ cha." },
  { id: "Trương Bào", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Zhang_Bao_statue.jpg", bio: "Con trai Trương Phi, tiếp nối sự nghiệp cha." },
  { id: "Khương Duy", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Jiang_Wei_statue.jpg", bio: "Đệ tử Gia Cát Lượng, lãnh đạo cuộc Bắc phạt cuối cùng." },
  { id: "Từ Thứ", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/7/7f/Xu_Shu_portrait.jpg", bio: "Mưu sĩ đầu tiên của Lưu Bị, tiến cử Khổng Minh rồi về với Tào Tháo." },
  { id: "Mã Lương", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/9/94/Ma_Liang_portrait.jpg", bio: "Anh trai Mã Tốc, tham mưu của Lưu Bị." },
  { id: "Mã Tốc", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/5/5d/Ma_Su_portrait.jpg", bio: "Tướng Thục bị Gia Cát Lượng xử trảm vì thất thủ Nhai Đình." },
  { id: "Phí Y", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Fei_Yi_portrait.jpg", bio: "Đại thần kế nhiệm Tưởng Uyển, chủ trì triều chính." },
  { id: "Đổng Hòa", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Dong_He_portrait.jpg", bio: "Quan lại thanh liêm thời Lưu Bị." },
  { id: "Tưởng Uyển", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Jiang_Wan_portrait.jpg/250px-Jiang_Wan_portrait.jpg", bio: "Thừa tướng Thục Hán sau Gia Cát Lượng." },
  { id: "Lý Nghiêm", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Li_Yan_portrait.jpg/250px-Li_Yan_portrait.jpg", bio: "Đồng sự của Gia Cát Lượng, sau bị phế truất." },
  { id: "Lưu Phong", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Liu_Feng_portrait.jpg/250px-Liu_Feng_portrait.jpg", bio: "Con nuôi Lưu Bị, không cứu viện Quan Vũ và bị xử tử." },
  { id: "Mi Chúc", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Mi_Zhu_portrait.jpg/250px-Mi_Zhu_portrait.jpg", bio: "Anh trai Mi Phương, ủng hộ Lưu Bị từ sớm." },
  { id: "Mi Phương", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Mi_Fang_portrait.jpg/250px-Mi_Fang_portrait.jpg", bio: "Em trai Mi Chúc, sau phản bội Lưu Bị." },
  { id: "Chu Thương", group: "Thục", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/GuanYu-ZhouCang.jpg/200px-GuanYu-ZhouCang.jpg", bio: "Chu Thương là một nhân vật hư cấu trong tác phẩm Tam quốc diễn nghĩa. Chu Thương rất ngưỡng mộ Quan Vũ, cam nguyện vứt bỏ tất cả để đi theo." },
  { id: "Dương Nghi", group: "Thục", avater: "https://static.wikia.nocookie.net/tam-quoc-sat/images/e/e0/Dn2.jpg/revision/latest?cb=20220511050347&path-prefix=vi", bio: "Ban đầu Dương Nghi theo phe Tào Tháo, làm chức chủ bạ dưới trướng thứ sử Kinh châu là Phó Quần. Ít lâu sau ông bỏ Tào Tháo theo Lưu Bị, chạy sang với Quan Vũ đang trấn thủ vùng Kinh châu thuộc Thục. Quan Vũ cho Dương Nghi làm công tào, rồi phái đến Tây Xuyên giúp Lưu Bị, sau được phong làm Thượng thư." },

  // Ngô
  { id: "Tôn Quyền", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Sun_Quan_portrait.jpg", bio: "Người sáng lập Đông Ngô, trị vì lâu dài và ổn định nhất trong Tam Quốc." },
  { id: "Chu Du", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Zhou_Yu_portrait.jpg", bio: "Đô đốc Đông Ngô, có vai trò quyết định trong chiến thắng Xích Bích." },
  { id: "Lỗ Túc", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Lu_Su_portrait.jpg", bio: "Quân sư kế nhiệm Chu Du, đóng vai trò quan trọng trong liên minh Ngô - Thục." },
  { id: "Tôn Sách", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/2/23/Sun_Ce_portrait.jpg", bio: "Anh trai Tôn Quyền, người đặt nền móng cho Đông Ngô." },
  { id: "Lữ Mông", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Lu_Meng_statue.jpg", bio: "Tướng Ngô giỏi chiến lược, nổi danh khi đánh bại Quan Vũ." },
  { id: "Cam Ninh", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Gan_Ning_statue.jpg", bio: "Dũng tướng Đông Ngô, nổi tiếng với các trận thủy chiến." },
  { id: "Trương Chiêu", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Zhang_Zhao_portrait.jpg", bio: "Mưu sĩ trụ cột của Đông Ngô, nổi tiếng với sự thận trọng." },
  { id: "Đại Kiều", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/3/3b/Da_Qiao.jpg", bio: "Vợ của Tôn Sách, một trong Nhị Kiều xinh đẹp." },
  { id: "Tiểu Kiều", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/2/23/Xiao_Qiao.jpg", bio: "Vợ của Chu Du, em gái Đại Kiều." },
  { id: "Lục Tốn", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Lu_Xun_portrait.jpg", bio: "Đại đô đốc Đông Ngô, chiến thắng trận Di Lăng." },
  { id: "Tôn Kiên", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Sun_Jian_portrait.jpg", bio: "Cha Tôn Sách - Tôn Quyền, khởi nghiệp nhà Đông Ngô." },
  { id: "Tôn Thượng Hương", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/6/69/Sun_Shangxiang.jpg", bio: "Em gái Tôn Quyền, kết hôn với Lưu Bị vì mục đích chính trị." },
  { id: "Trình Phổ", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Cheng_Pu_statue.jpg", bio: "Lão tướng tam triều, tham gia trận Xích Bích." },
  { id: "Chu Thái", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Zhou_Tai_portrait.jpg", bio: "Dũng tướng cứu Tôn Quyền nhiều lần." },
  { id: "Từ Thịnh", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/6/60/Xu_Sheng_statue.jpg", bio: "Danh tướng phòng thủ biên cương." },
  { id: "Đinh Phụng", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/8/83/Ding_Feng_statue.jpg", bio: "Tướng lĩnh nổi tiếng qua các đời chúa Ngô." },
  { id: "Hoàng Cái", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Huang_Gai_statue.jpg/250px-Huang_Gai_statue.jpg", bio: "Lão tướng Ngô, dùng khổ nhục kế trong trận Xích Bích." },
  { id: "Hàn Đương", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Han_Dang_statue.jpg/250px-Han_Dang_statue.jpg", bio: "Tướng lĩnh kỳ cựu của Đông Ngô." },
  { id: "Tưởng Khâm", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Jiang_Qin_statue.jpg/250px-Jiang_Qin_statue.jpg", bio: "Tướng lĩnh thủy quân của Đông Ngô." },
  { id: "Phan Chương", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Pan_Zhang_statue.jpg/250px-Pan_Zhang_statue.jpg", bio: "Tướng Ngô bắt được Quan Vũ." },
  { id: "Bộ Chất", group: "Ngô", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Bu_Zhi_portrait.jpg/250px-Bu_Zhi_portrait.jpg", bio: "Quan lại và tướng lĩnh Đông Ngô." },

  // Ngụy
  { id: "Tào Tháo", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Cao_Cao_portrait.jpg", bio: "Thủ lĩnh Ngụy quốc, nhà chiến lược và chính trị lỗi lạc thời Tam Quốc." },
  { id: "Tuân Úc", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/6/64/Xun_Yu_portrait.jpg", bio: "Mưu sĩ chủ lực của Tào Tháo, có công lớn trong việc xây dựng nền móng Ngụy quốc." },
  { id: "Tuân Du", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/6/64/Xun_Yu_portrait.jpg", bio: "Tự Công Đạt (公達), là một là một mưu sĩ giỏi của Tào Tháo." },
  { id: "Quách Gia", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Guo_Jia_portrait.jpg", bio: "Quân sư Tào Tháo, nổi tiếng với tài tiên liệu chiến cục." },
  { id: "Tào Phi", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Cao_Pi_portrait.jpg", bio: "Con trai Tào Tháo, lập ra nhà Ngụy và trở thành Ngụy Văn Đế." },
  { id: "Tào Nhân", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/2/2b/Cao_Ren_statue.jpg", bio: "Tướng lĩnh trung thành, có công lớn trong các chiến dịch của Tào Tháo." },
  { id: "Tào Hồng", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Cao_Hong_statue.jpg", bio: "Cận thần và tướng giỏi của Tào Tháo, từng cứu mạng Tào Tháo khi gặp nguy." },
  { id: "Trình Dục", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Cheng_Yu_portrait.jpg", bio: "Mưu sĩ của Tào Tháo, nổi tiếng với mưu kế hiểm độc." },
  { id: "Hạ Hầu Đôn", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Xiahou_Dun_statue.jpg", bio: "Tướng lĩnh trụ cột của Tào Ngụy, bị mù một mắt." },
  { id: "Hạ Hầu Uyên", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/9/92/Xiahou_Yuan_statue.jpg", bio: "Tướng lĩnh tài năng của Tào Ngụy, tử trận tại Định Quân Sơn." },
  { id: "Tư Mã Ý", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/e/e1/Sima_Yi_portrait.jpg", bio: "Nhà chiến lược và chính trị gia tài ba, đặt nền móng cho nhà Tấn." },
  { id: "Tào Chân", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Cao_Zhen_portrait.jpg", bio: "Tướng lĩnh quan trọng của Tào Ngụy." },
  { id: "Hứa Chử", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Xu_Chu_statue.jpg", bio: "Dũng tướng thân cận Tào Tháo, biệt danh 'Hổ Si'." },
  { id: "Trương Cáp", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/4/44/Zhang_He_statue.jpg", bio: "Danh tướng kỳ cựu qua 4 đời chúa Ngụy." },
  { id: "Tư Mã Sư", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/3/38/Sima_Shi_portrait.jpg", bio: "Con trưởng Tư Mã Ý, mở đường cho nhà Tấn." },
  { id: "Tư Mã Chiêu", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/7/7f/Sima_Zhao_portrait.jpg", bio: "Con thứ Tư Mã Ý, cha của Tư Mã Viêm (Tấn Vũ Đế)." },
  { id: "Đặng Ngải", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/4/45/Deng_Ai_statue.jpg", bio: "Danh tướng có công diệt Thục Hán." },
  { id: "Hạ Hầu Bá", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/3/39/Xiahou_Ba_portrait.jpg", bio: "Con Hạ Hầu Uyên, sau đầu hàng Thục Hán." },
  { id: "Vương Lãng", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Wang_Lang_portrait.jpg/250px-Wang_Lang_portrait.jpg", bio: "Quan lại nhà Hán và Ngụy, nổi tiếng với cuộc tranh luận với Gia Cát Lượng." },
  { id: "Giả Hủ", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Jia_Xu_portrait.jpg/250px-Jia_Xu_portrait.jpg", bio: "Mưu sĩ tài ba, phục vụ nhiều thế lực trước khi theo Tào Tháo." },
  { id: "Man Sủng", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Man_Chong_portrait.jpg/250px-Man_Chong_portrait.jpg", bio: "Tướng lĩnh và quan lại của Tào Ngụy." },
  { id: "Văn Sính", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Wen_Pin_portrait.jpg/250px-Wen_Pin_portrait.jpg", bio: "Tướng lĩnh phục vụ Lưu Biểu trước khi đầu hàng Tào Tháo." },
  { id: "Quách Hoài", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Guo_Huai_portrait.jpg/250px-Guo_Huai_portrait.jpg", bio: "Tướng lĩnh quan trọng của Tào Ngụy, phòng thủ phía tây." },
  { id: "Tào Duệ", group: "Ngụy", avatar: "null", bio: "Tào Ngụy Minh Đế (chữ Hán: 曹魏明帝; 204 - 22 tháng 1, 239), tên thật Tào Duệ (tiếng Trung: 曹叡; bính âm: Cáo Rùi), tự Nguyên Trọng (元仲), là vị Hoàng đế thứ hai của triều Tào Ngụy trong lịch sử Trung Quốc. Ông trị vì từ năm 226 đến 239, tổng 13 năm." },
  { id: "Lưu Tông", group: "Ngụy", avatar: "null", bio: "Lưu Tông (chữ Hán: 劉琮; 191-?) là Châu mục Kinh châu đầu thời Tam Quốc trong lịch sử Trung Quốc. Ông kế nghiệp Lưu Biểu ở Kinh châu trong một thời gian ngắn và quy hàng Tào Tháo." },

  // Quần hùng
  { id: "Viên Thiệu", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/d/d2/Yuan_Shao_statue.jpg", bio: "Lãnh chúa phương Bắc, thất bại tại Quan Độ trước Tào Tháo." },
  { id: "Đổng Trác", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Dong_Zhuo_portrait.jpg", bio: "Lộng quyền triều đình, bị liên minh các chư hầu đánh bại." },
  { id: "Lữ Bố", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Lu_Bu_statue.jpg", bio: "Võ tướng vô địch, nhưng phản trắc và cuối cùng bị giết bởi Tào Tháo." },
  { id: "Điêu Thuyền", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Diao_Chan.jpg", bio: "Một trong Tứ đại mỹ nhân Trung Hoa, đóng vai trò quan trọng trong cái chết của Đổng Trác." },
  { id: "Trần Cung", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/0/00/Chen_Gong_portrait.jpg", bio: "Mưu sĩ tài ba, từng giúp Lữ Bố chống lại Tào Tháo." },
  { id: "Viên Thuật", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Yuan_Shu_portrait.jpg", bio: "Lãnh chúa tự xưng đế, bị các thế lực khác tiêu diệt." },
  { id: "Trương Giác", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/0/06/Zhang_Jue_statue.jpg", bio: "Lãnh đạo cuộc khởi nghĩa khăn vàng." },
  { id: "Hoàng Cân", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/0/00/Yellow_Turban_rebellion.jpg", bio: "Quân đội khởi nghĩa khăn vàng." },
  { id: "Hoa Hùng", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Hua_Xiong_statue.jpg", bio: "Tướng Đổng Trác bị Quan Vũ chém." },
  { id: "Nhan Lương", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/1/16/Yan_Liang_statue.jpg", bio: "Tướng Viên Thiệu bị Quan Vũ đánh bại." },
  { id: "Văn Xú", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/8/8b/Wen_Chou_statue.jpg", bio: "Tướng Viên Thiệu bị Quan Vũ giết." },
  { id: "Hứa Du", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Xu_You_portrait.jpg", bio: "Mưu sĩ phản Viên Thiệu theo Tào Tháo." },
  { id: "Trương Lỗ", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/1/1f/Zhang_Lu_portrait.jpg", bio: "Thủ lĩnh Ngũ Đấu Mễ Đạo, cát cứ ở Hán Trung." },
  { id: "Mạnh Hoạch", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Meng_Huo_statue.jpg", bio: "Thủ lĩnh Nam Man bị Khổng Minh bảy lần bắt và thả." },
  { id: "Chúc Dung", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Zhu_Rong_statue.jpg/250px-Zhu_Rong_statue.jpg", bio: "Vợ của Mạnh Hoạch, nữ tướng dũng mãnh của Nam Man." },
  { id: "Công Tôn Toản", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Gongsun_Zan_portrait.jpg/250px-Gongsun_Zan_portrait.jpg", bio: "Lãnh chúa ở U Châu, từng giao chiến với Viên Thiệu." },
  { id: "Đào Khiêm", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Tao_Qian_portrait.jpg/250px-Tao_Qian_portrait.jpg", bio: "Thứ sử Từ Châu, nhường Từ Châu cho Lưu Bị." },
  { id: "Lưu Biểu", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Liu_Biao_Qing_portait.jpg/250px-Liu_Biao_Qing_portait.jpg", bio: "Mục Kinh Châu, cai trị Kinh Châu trước khi qua đời." },
  { id: "Hoàng Tổ", group: "Quần hùng", avatar: "https://danviet.ex-cdn.com/files/f1/upload/3-2019/images/2019-08-27/Khong-phai-Quan-Vu-day-moi-la-ho-tuong-chet-tuc-tuoi-nhat-Tam-Quoc-671-1566888828-width498height456.jpg", bio: "Hoàng Tổ theo phục vụ Lưu Biểu và trở thành bộ tướng của Lưu Biểu. Ông được Lưu Biểu giao phụ trách thủy quân." },
  { id: "Lưu Chương", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Liu_Zhang_portrait.jpg/250px-Liu_Zhang_portrait.jpg", bio: "Con trai Lưu Yên, Mục Ích Châu, bị Lưu Bị chiếm Ích Châu." },
  { id: "Trương Tú", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Zhang_Xiu_portrait.jpg/250px-Zhang_Xiu_portrait.jpg", bio: "Lãnh chúa ở Uyển Thành, từng giao chiến với Tào Tháo." },
  { id: "Sái Mạo", group: "Quần hùng", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Cai_Mao_portrait.jpg/250px-Cai_Mao_portrait.jpg", bio: "Tướng lĩnh Kinh Châu, sau đầu hàng Tào Tháo." },
  
  // Trung lập/Khác
  { id: "Hoa Đà", group: "Khác", avatar: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Hua_Tuo_statue.jpg", bio: "Thần y nổi tiếng thời Tam Quốc." },
  { id: "Vương Doãn", group: "Khác", avatar: "https://upload.wikimedia.org/wikipedia/commons/8/8d/Wang_Yun_portrait.jpg", bio: "Quan Tư đồ nhà Hán, dùng Điêu Thuyền để ly gián Đổng Trác và Lữ Bố." },
  { id: "Trương Liêu", group: "Ngụy", avatar: "https://upload.wikimedia.org/wikipedia/commons/1/19/Zhang_Liao_statue.jpg", bio: "Danh tướng Tào Ngụy, nổi tiếng với trận Hợp Phì." },
  { id: "Tả Từ", group: "Khác", avatar: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Zuo_Ci_portrait.jpg", bio: "Đạo sĩ tiên tri nổi tiếng thời Tam Quốc." },
  { id: "Vu Cát", group: "Khác", avatar: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Yu_Ji_portrait.jpg", bio: "Đạo sĩ bị Tôn Sách xử tử." },
  { id: "Thái Văn Cơ", group: "Khác", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Cai_Wenji_portrait.jpg/250px-Cai_Wenji_portrait.jpg", bio: "Nữ sĩ tài năng, con gái Thái Ung, bị Hung Nô bắt cóc rồi được Tào Tháo chuộc về." },
  { id: "Khổng Dung", group: "Khác", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Kong_Rong_portrait.jpg/250px-Kong_Rong_portrait.jpg", bio: "Nhà Nho nổi tiếng, hậu duệ Khổng Tử, bị Tào Tháo giết." },
  { id: "Mê Hành", group: "Khác", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Mi_Heng_portrait.jpg/250px-Mi_Heng_portrait.jpg", bio: "Nhà Nho tài năng nhưng ngông cuồng, bị Hoàng Tổ giết." },
  { id: "Tào Tung", group: "Khác", avatar: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Cao_Cao_portrait.jpg", bio: "Là đại thần nhà Đông Hán. Cha của Tào Tháo, ông của hoàng đế khai quốc nhà Tào Ngụy là Tào Phi." },
  { id: "Lưu Kỳ", group: "Khác", avatar: "null", bio: "Lưu Kỳ (chữ Hán: 劉琦; 173-210) là Thứ sử Kinh châu đầu thời Tam Quốc trong lịch sử Trung Quốc." },

  // Giao điểm trận Xích Bích
  { id: "Trận Xích Bích", group: "Trận chiến", avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Red_Cliffs_battle_map.jpg/640px-Red_Cliffs_battle_map.jpg", bio: "Trận đánh kinh điển giữa quân Tào và liên minh Tôn - Lưu, quyết định cục diện Tam Quốc." }
];

const links = [
  { source: "Lưu Bị", target: "Quan Vũ", "type": "sibling" },
  { source: "Lưu Bị", target: "Trương Phi", "type": "sibling" },
  { source: "Lưu Bị", target: "Gia Cát Lượng", "type": "mentor" },
  { source: "Lưu Bị", target: "Triệu Vân", "type": "ally" },
  { source: "Lưu Bị", target: "Pháp Chính", "type": "ally" },
  { source: "Lưu Bị", target: "Bàng Thống", "type": "ally" },
  { source: "Lưu Bị", target: "Hoàng Nguyệt Anh", "type": "spouse" },
  { source: "Lưu Bị", target: "A Đẩu", "type": "parent" },
  { source: "Lưu Bị", target: "Quan Bình", "type": "adopted" },
  { source: "Lưu Bị", target: "Lưu Phong", "type": "adopted" },
  { source: "Lưu Bị", target: "Mi Chúc", "type": "ally" },
  { source: "Lưu Bị", target: "Mi Phương", "type": "ally" },
  { source: "Lưu Bị", target: "Tôn Quyền", "type": "interact" },
  { source: "Lưu Bị", target: "Tào Tháo", "type": "enemy" },
  { source: "Lưu Bị", target: "Đổng Trác", "type": "enemy" },
  { source: "Lưu Bị", target: "Lữ Bố", "type": "enemy" },
  { source: "Lưu Bị", target: "Viên Thiệu", "type": "interact" },
  { source: "Lưu Bị", target: "Đào Khiêm", "type": "interact" },
  { source: "Lưu Bị", target: "Lưu Biểu", "type": "relative" },
  { source: "Lưu Bị", target: "Lưu Chương", "type": "relative" },
  { source: "Quan Vũ", target: "Trương Phi", "type": "sibling" },
  { source: "Quan Vũ", target: "Lưu Bị", "type": "sibling" },
  { source: "Quan Vũ", target: "Gia Cát Lượng", "type": "ally" },
  { source: "Quan Vũ", target: "Triệu Vân", "type": "ally" },
  { source: "Quan Vũ", target: "Quan Bình", "type": "parent" },
  { source: "Quan Vũ", target: "Quan Hưng", "type": "parent" },
  { source: "Quan Vũ", target: "Chu Thương", "type": "ally" },
  { source: "Quan Vũ", target: "Tào Tháo", "type": "enemy" },
  { source: "Quan Vũ", target: "Lữ Mông", "type": "enemy" },
  { source: "Trương Phi", target: "Quan Vũ", "type": "sibling" },
  { source: "Trương Phi", target: "Lưu Bị", "type": "sibling" },
  { source: "Trương Phi", target: "Gia Cát Lượng", "type": "ally" },
  { source: "Trương Phi", target: "Triệu Vân", "type": "ally" },
  { source: "Trương Phi", target: "Trương Bào", "type": "parent" },
  { source: "Trương Phi", target: "Lữ Bố", "type": "enemy" },
  { source: "Trương Phi", target: "Tào Tháo", "type": "enemy" },
  { source: "Gia Cát Lượng", target: "Lưu Bị", "type": "mentor" },
  { source: "Gia Cát Lượng", target: "Quan Vũ", "type": "ally" },
  { source: "Gia Cát Lượng", target: "Trương Phi", "type": "ally" },
  { source: "Gia Cát Lượng", target: "Triệu Vân", "type": "ally" },
  { source: "Gia Cát Lượng", target: "Ngụy Diên", "type": "ally" },
  { source: "Gia Cát Lượng", target: "Mã Siêu", "type": "ally" },
  { source: "Gia Cát Lượng", target: "Hoàng Trung", "type": "ally" },
  { source: "Gia Cát Lượng", target: "Pháp Chính", "type": "ally" },
  { source: "Gia Cát Lượng", target: "Bàng Thống", "type": "ally" },
  { source: "Gia Cát Lượng", target: "Hoàng Nguyệt Anh", "type": "spouse" },
  { source: "Gia Cát Lượng", target: "Khương Duy", "type": "successor" },
  { source: "Gia Cát Lượng", target: "Từ Thứ", "type": "mentor" },
  { source: "Gia Cát Lượng", target: "Mã Lương", "type": "ally" },
  { source: "Gia Cát Lượng", target: "Mã Tốc", "type": "ally" },
  { source: "Gia Cát Lượng", target: "Phí Y", "type": "ally" },
  { source: "Gia Cát Lượng", target: "Đổng Hòa", "type": "ally" },
  { source: "Gia Cát Lượng", target: "Tưởng Uyển", "type": "ally" },
  { source: "Gia Cát Lượng", target: "Lý Nghiêm", "type": "interact" },
  { source: "Gia Cát Lượng", target: "Tào Tháo", "type": "enemy" },
  { source: "Gia Cát Lượng", target: "Tư Mã Ý", "type": "enemy" },
  { source: "Triệu Vân", target: "Lưu Bị", "type": "ally" },
  { source: "Triệu Vân", target: "Quan Vũ", "type": "ally" },
  { source: "Triệu Vân", target: "Trương Phi", "type": "ally" },
  { source: "Triệu Vân", target: "Gia Cát Lượng", "type": "ally" },
  { source: "Triệu Vân", target: "A Đẩu", "type": "interact" },
  { source: "Triệu Vân", target: "Tào Tháo", "type": "enemy" },
  { source: "Ngụy Diên", target: "Gia Cát Lượng", "type": "ally" },
  { source: "Ngụy Diên", target: "Lưu Bị", "type": "ally" },
  { source: "Ngụy Diên", target: "Dương Nghi", "type": "enemy" },
  { source: "Mã Siêu", target: "Lưu Bị", "type": "ally" },
  { source: "Mã Siêu", target: "Gia Cát Lượng", "type": "ally" },
  { source: "Mã Siêu", target: "Mã Đại", "type": "relative" },
  { source: "Mã Siêu", target: "Tào Tháo", "type": "enemy" },
  { source: "Hoàng Trung", target: "Lưu Bị", "type": "ally" },
  { source: "Hoàng Trung", target: "Gia Cát Lượng", "type": "ally" },
  { source: "Hoàng Trung", target: "Quan Vũ", "type": "interact" },
  { source: "Hoàng Trung", target: "Tào Tháo", "type": "enemy" },
  { source: "Pháp Chính", target: "Lưu Bị", "type": "ally" },
  { source: "Pháp Chính", target: "Gia Cát Lượng", "type": "ally" },
  { source: "Lưu Chương", target: "Pháp Chính", "type": "interact" },
  { source: "Bàng Thống", target: "Lưu Bị", "type": "ally" },
  { source: "Bàng Thống", target: "Gia Cát Lượng", "type": "ally" },
  { source: "Bàng Thống", target: "Tôn Quyền", "type": "interact" },
  { source: "Hoàng Nguyệt Anh", target: "Lưu Bị", "type": "spouse" },
  { source: "Hoàng Nguyệt Anh", target: "Gia Cát Lượng", "type": "spouse" },
  { source: "A Đẩu", target: "Lưu Bị", "type": "parent" },
  { source: "A Đẩu", target: "Gia Cát Lượng", "type": "interact" },
  { source: "A Đẩu", target: "Triệu Vân", "type": "interact" },
  { source: "A Đẩu", target: "Khương Duy", "type": "interact" },
  { source: "Mã Đại", target: "Mã Siêu", "type": "relative" },
  { source: "Mã Đại", target: "Gia Cát Lượng", "type": "ally" },
  { source: "Quan Bình", target: "Quan Vũ", "type": "parent" },
  { source: "Quan Bình", target: "Lưu Bị", "type": "adopted" },
  { source: "Quan Bình", target: "Chu Thương", "type": "ally" },
  { source: "Quan Hưng", target: "Quan Vũ", "type": "parent" },
  { source: "Trương Bào", target: "Trương Phi", "type": "parent" },
  { source: "Khương Duy", target: "Gia Cát Lượng", "type": "successor" },
  { source: "Khương Duy", target: "A Đẩu", "type": "ally" },
  { source: "Khương Duy", target: "Tưởng Uyển", "type": "ally" },
  { source: "Khương Duy", target: "Đặng Ngải", "type": "enemy" },
  { source: "Từ Thứ", target: "Lưu Bị", "type": "mentor" },
  { source: "Từ Thứ", target: "Gia Cát Lượng", "type": "recommend" },
  { source: "Từ Thứ", target: "Tào Tháo", "type": "ally" },
  { source: "Mã Lương", target: "Lưu Bị", "type": "ally" },
  { source: "Mã Lương", target: "Gia Cát Lượng", "type": "ally" },
  { source: "Mã Tốc", target: "Lưu Bị", "type": "ally" },
  { source: "Mã Tốc", target: "Gia Cát Lượng", "type": "ally" },
  { source: "Mã Tốc", target: "Tư Mã Ý", "type": "enemy" },
  { source: "Phí Y", target: "Lưu Bị", "type": "ally" },
  { source: "Phí Y", target: "Gia Cát Lượng", "type": "ally" },
  { source: "Phí Y", target: "Tưởng Uyển", "type": "successor" },
  { source: "Đổng Hòa", target: "Lưu Bị", "type": "ally" },
  { source: "Đổng Hòa", target: "Gia Cát Lượng", "type": "ally" },
  { source: "Tưởng Uyển", target: "Lưu Bị", "type": "ally" },
  { source: "Tưởng Uyển", target: "Gia Cát Lượng", "type": "ally" },
  { source: "Tưởng Uyển", target: "Phí Y", "type": "successor" },
  { source: "Tưởng Uyển", target: "Khương Duy", "type": "ally" },
  { source: "Lý Nghiêm", target: "Lưu Bị", "type": "ally" },
  { source: "Lý Nghiêm", target: "Gia Cát Lượng", "type": "interact" },
  { source: "Lưu Phong", target: "Lưu Bị", "type": "adopted" },
  { source: "Lưu Phong", target: "Quan Vũ", "type": "interact" },
  { source: "Mi Chúc", target: "Lưu Bị", "type": "ally" },
  { source: "Mi Phương", target: "Lưu Bị", "type": "ally" },
  { source: "Mi Phương", target: "Quan Vũ", "type": "enemy" },
  { source: "Chu Thương", target: "Quan Vũ", "type": "ally" },
  { source: "Chu Thương", target: "Lưu Bị", "type": "ally" },
  { source: "Quan Bình", target: "Chu Thương", "type": "ally" },
  { source: "Tôn Quyền", target: "Tôn Sách", "type": "sibling" },
  { source: "Tôn Quyền", target: "Chu Du", "type": "ally" },
  { source: "Tôn Quyền", target: "Lỗ Túc", "type": "ally" },
  { source: "Tôn Quyền", target: "Lữ Mông", "type": "ally" },
  { source: "Tôn Quyền", target: "Cam Ninh", "type": "ally" },
  { source: "Tôn Quyền", target: "Trương Chiêu", "type": "ally" },
  { source: "Tôn Quyền", target: "Đại Kiều", "type": "relative" },
  { source: "Tôn Quyền", target: "Tiểu Kiều", "type": "relative" },
  { source: "Tôn Quyền", target: "Lục Tốn", "type": "ally" },
  { source: "Tôn Quyền", target: "Tôn Kiên", "type": "parent" },
  { source: "Tôn Quyền", target: "Tôn Thượng Hương", "type": "sibling" },
  { source: "Tôn Quyền", target: "Trình Phổ", "type": "ally" },
  { source: "Tôn Quyền", target: "Chu Thái", "type": "ally" },
  { source: "Tôn Quyền", target: "Từ Thịnh", "type": "ally" },
  { source: "Tôn Quyền", target: "Đinh Phụng", "type": "ally" },
  { source: "Tôn Quyền", target: "Hoàng Cái", "type": "ally" },
  { source: "Tôn Quyền", target: "Hàn Đương", "type": "ally" },
  { source: "Tôn Quyền", target: "Tưởng Khâm", "type": "ally" },
  { source: "Tôn Quyền", target: "Phan Chương", "type": "ally" },
  { source: "Tôn Quyền", target: "Bộ Chất", "type": "ally" },
  { source: "Tôn Quyền", target: "Lưu Bị", "type": "interact" },
  { source: "Tôn Quyền", target: "Tào Tháo", "type": "enemy" },
  { source: "Chu Du", target: "Tôn Sách", "type": "ally" },
  { source: "Chu Du", target: "Tôn Quyền", "type": "ally" },
  { source: "Chu Du", target: "Lỗ Túc", "type": "ally" },
  { source: "Chu Du", target: "Tiểu Kiều", "type": "spouse" },
  { source: "Chu Du", target: "Lưu Bị", "type": "enemy" },
  { source: "Chu Du", target: "Gia Cát Lượng", "type": "enemy" },
  { source: "Lỗ Túc", target: "Tôn Quyền", "type": "ally" },
  { source: "Lỗ Túc", target: "Chu Du", "type": "ally" },
  { source: "Lỗ Túc", target: "Lưu Bị", "type": "ally" },
  { source: "Lỗ Túc", target: "Gia Cát Lượng", "type": "ally" },
  { source: "Tôn Sách", target: "Tôn Kiên", "type": "parent" },
  { source: "Tôn Sách", target: "Tôn Quyền", "type": "sibling" },
  { source: "Tôn Sách", target: "Chu Du", "type": "ally" },
  { source: "Tôn Sách", target: "Đại Kiều", "type": "spouse" },
  { source: "Lữ Mông", target: "Tôn Quyền", "type": "ally" },
  { source: "Lữ Mông", target: "Lỗ Túc", "type": "successor" },
  { source: "Lữ Mông", target: "Quan Vũ", "type": "enemy" },
  { source: "Cam Ninh", target: "Tôn Quyền", "type": "ally" },
  { source: "Cam Ninh", target: "Lưu Bị", "type": "interact" },
  { source: "Trương Chiêu", target: "Tôn Quyền", "type": "ally" },
  { source: "Trương Chiêu", target: "Tôn Sách", "type": "ally" },
  { source: "Đại Kiều", target: "Tôn Sách", "type": "spouse" },
  { source: "Đại Kiều", target: "Tôn Quyền", "type": "relative" },
  { source: "Tiểu Kiều", target: "Chu Du", "type": "spouse" },
  { source: "Tiểu Kiều", target: "Tôn Quyền", "type": "relative" },
  { source: "Lục Tốn", target: "Tôn Quyền", "type": "ally" },
  { source: "Lục Tốn", target: "Lữ Mông", "type": "ally" },
  { source: "Lục Tốn", target: "Lưu Bị", "type": "enemy" },
  { source: "Tôn Kiên", target: "Tôn Sách", "type": "parent" },
  { source: "Tôn Kiên", target: "Tôn Quyền", "type": "parent" },
  { source: "Tôn Kiên", target: "Tôn Thượng Hương", "type": "parent" },
  { source: "Tôn Kiên", target: "Đổng Trác", "type": "enemy" },
  { source: "Tôn Thượng Hương", target: "Tôn Kiên", "type": "parent" },
  { source: "Tôn Thượng Hương", target: "Tôn Quyền", "type": "sibling" },
  { source: "Tôn Thượng Hương", target: "Lưu Bị", "type": "spouse" },
  { source: "Trình Phổ", target: "Tôn Kiên", "type": "ally" },
  { source: "Trình Phổ", target: "Tôn Sách", "type": "ally" },
  { source: "Trình Phổ", target: "Tôn Quyền", "type": "ally" },
  { source: "Chu Thái", target: "Tôn Sách", "type": "ally" },
  { source: "Chu Thái", target: "Tôn Quyền", "type": "ally" },
  { source: "Từ Thịnh", target: "Tôn Quyền", "type": "ally" },
  { source: "Đinh Phụng", target: "Tôn Quyền", "type": "ally" },
  { source: "Hoàng Cái", target: "Tôn Kiên", "type": "ally" },
  { source: "Hoàng Cái", target: "Tôn Sách", "type": "ally" },
  { source: "Hoàng Cái", target: "Tôn Quyền", "type": "ally" },
  { source: "Hàn Đương", target: "Tôn Kiên", "type": "ally" },
  { source: "Hàn Đương", target: "Tôn Sách", "type": "ally" },
  { source: "Hàn Đương", target: "Tôn Quyền", "type": "ally" },
  { source: "Tưởng Khâm", target: "Tôn Sách", "type": "ally" },
  { source: "Tưởng Khâm", target: "Tôn Quyền", "type": "ally" },
  { source: "Phan Chương", target: "Tôn Quyền", "type": "ally" },
  { source: "Phan Chương", target: "Quan Vũ", "type": "enemy" },
  { source: "Bộ Chất", target: "Tôn Quyền", "type": "ally" },
  { source: "Tào Tháo", target: "Tào Tung", "type": "parent" },
  { source: "Tào Tháo", target: "Tào Phi", "type": "parent" },
  { source: "Tào Tháo", target: "Tuân Úc", "type": "ally" },
  { source: "Tào Tháo", target: "Quách Gia", "type": "ally" },
  { source: "Tào Tháo", target: "Tào Nhân", "type": "relative" },
  { source: "Tào Tháo", target: "Tào Hồng", "type": "relative" },
  { source: "Tào Tháo", target: "Trình Dục", "type": "ally" },
  { source: "Tào Tháo", target: "Hạ Hầu Đôn", "type": "relative" },
  { source: "Tào Tháo", target: "Hạ Hầu Uyên", "type": "relative" },
  { source: "Tào Tháo", target: "Tư Mã Ý", "type": "ally" },
  { source: "Tào Tháo", target: "Tào Chân", "type": "adopted" },
  { source: "Tào Tháo", target: "Hứa Chử", "type": "ally" },
  { source: "Tào Tháo", target: "Trương Liêu", "type": "ally" },
  { source: "Tào Tháo", target: "Trương Cáp", "type": "ally" },
  { source: "Tào Tháo", target: "Giả Hủ", "type": "ally" },
  { source: "Tào Tháo", target: "Điêu Thuyền", "type": "interact" },
  { source: "Tào Tháo", target: "Lữ Bố", "type": "enemy" },
  { source: "Tào Tháo", target: "Đổng Trác", "type": "enemy" },
  { source: "Tào Tháo", target: "Viên Thiệu", "type": "enemy" },
  { source: "Tào Tháo", target: "Lưu Bị", "type": "enemy" },
  { source: "Tào Tháo", target: "Tôn Quyền", "type": "enemy" },
  { source: "Tào Tháo", target: "Trương Tú", "type": "ally" },
  { source: "Tào Tháo", target: "Thái Văn Cơ", "type": "interact" },
  { source: "Tuân Úc", target: "Tào Tháo", "type": "ally" },
  { source: "Tuân Úc", target: "Tuân Du", "type": "relative" },
  { source: "Quách Gia", target: "Tào Tháo", "type": "ally" },
  { source: "Tào Phi", target: "Tào Tháo", "type": "parent" },
  { source: "Tào Phi", target: "Tào Duệ", "type": "parent" },
  { source: "Tào Phi", target: "Tư Mã Ý", "type": "ally" },
  { source: "Tào Nhân", target: "Tào Tháo", "type": "relative" },
  { source: "Tào Nhân", target: "Tào Hồng", "type": "sibling" },
  { source: "Tào Hồng", target: "Tào Tháo", "type": "relative" },
  { source: "Tào Hồng", target: "Tào Nhân", "type": "sibling" },
  { source: "Trình Dục", target: "Tào Tháo", "type": "ally" },
  { source: "Hạ Hầu Đôn", target: "Tào Tháo", "type": "relative" },
  { source: "Hạ Hầu Uyên", target: "Tào Tháo", "type": "relative" },
  { source: "Tư Mã Ý", target: "Tào Tháo", "type": "ally" },
  { source: "Tư Mã Ý", target: "Tào Phi", "type": "ally" },
  { source: "Tư Mã Ý", target: "Tư Mã Sư", "type": "parent" },
  { source: "Tư Mã Ý", target: "Tư Mã Chiêu", "type": "parent" },
  { source: "Tư Mã Ý", target: "Gia Cát Lượng", "type": "enemy" },
  { source: "Tào Chân", target: "Tào Tháo", "type": "adopted" },
  { source: "Tào Chân", target: "Tào Phi", "type": "ally" },
  { source: "Hứa Chử", target: "Tào Tháo", "type": "ally" },
  { source: "Trương Cáp", target: "Tào Tháo", "type": "ally" },
  { source: "Trương Cáp", target: "Gia Cát Lượng", "type": "enemy" },
  { source: "Tư Mã Sư", target: "Tư Mã Ý", "type": "parent" },
  { source: "Tư Mã Sư", target: "Tư Mã Chiêu", "type": "sibling" },
  { source: "Tư Mã Chiêu", target: "Tư Mã Ý", "type": "parent" },
  { source: "Tư Mã Chiêu", target: "Tư Mã Sư", "type": "sibling" },
  { source: "Đặng Ngải", target: "Tư Mã Chiêu", "type": "ally" },
  { source: "Đặng Ngải", target: "Khương Duy", "type": "enemy" },
  { source: "Hạ Hầu Bá", target: "Hạ Hầu Uyên", "type": "parent" },
  { source: "Hạ Hầu Bá", target: "Khương Duy", "type": "ally" },
  { source: "Vương Lãng", target: "Tào Tháo", "type": "ally" },
  { source: "Vương Lãng", target: "Gia Cát Lượng", "type": "enemy" },
  { source: "Giả Hủ", target: "Đổng Trác", "type": "ally" },
  { source: "Giả Hủ", target: "Trương Tú", "type": "ally" },
  { source: "Giả Hủ", target: "Tào Tháo", "type": "ally" },
  { source: "Man Sủng", target: "Tào Tháo", "type": "ally" },
  { source: "Văn Sính", target: "Lưu Biểu", "type": "ally" },
  { source: "Văn Sính", target: "Tào Tháo", "type": "ally" },
  { source: "Quách Hoài", target: "Tào Phi", "type": "ally" },
  { source: "Quách Hoài", target: "Tư Mã Ý", "type": "ally" },
  { source: "Viên Thiệu", target: "Viên Thuật", "type": "sibling" },
  { source: "Viên Thiệu", target: "Tào Tháo", "type": "enemy" },
  { source: "Viên Thiệu", target: "Công Tôn Toản", "type": "enemy" },
  { source: "Đổng Trác", target: "Lữ Bố", "type": "adopted" },
  { source: "Đổng Trác", target: "Vương Doãn", "type": "enemy" },
  { source: "Đổng Trác", target: "Tào Tháo", "type": "enemy" },
  { source: "Đổng Trác", target: "Tôn Kiên", "type": "enemy" },
  { source: "Đổng Trác", target: "Lưu Bị", "type": "enemy" },
  { source: "Lữ Bố", target: "Đổng Trác", "type": "adopted" },
  { source: "Lữ Bố", target: "Điêu Thuyền", "type": "spouse" },
  { source: "Lữ Bố", target: "Trần Cung", "type": "ally" },
  { source: "Lữ Bố", target: "Tào Tháo", "type": "enemy" },
  { source: "Lữ Bố", target: "Lưu Bị", "type": "enemy" },
  { source: "Lữ Bố", target: "Trương Phi", "type": "enemy" },
  { source: "Điêu Thuyền", target: "Vương Doãn", "type": "adopted" },
  { source: "Điêu Thuyền", target: "Lữ Bố", "type": "spouse" },
  { source: "Điêu Thuyền", target: "Đổng Trác", "type": "interact" },
  { source: "Điêu Thuyền", target: "Tào Tháo", "type": "interact" },
  { source: "Trần Cung", target: "Tào Tháo", "type": "enemy" },
  { source: "Trần Cung", target: "Lữ Bố", "type": "ally" },
  { source: "Viên Thuật", target: "Viên Thiệu", "type": "sibling" },
  { source: "Viên Thuật", target: "Tào Tháo", "type": "enemy" },
  { source: "Trương Giác", target: "Hoàng Cân", "type": "leader" },
  { source: "Hoàng Cân", target: "Trương Giác", "type": "leader" },
  { source: "Hoa Hùng", target: "Đổng Trác", "type": "ally" },
  { source: "Hoa Hùng", target: "Quan Vũ", "type": "enemy" },
  { source: "Nhan Lương", target: "Viên Thiệu", "type": "ally" },
  { source: "Nhan Lương", target: "Quan Vũ", "type": "enemy" },
  { source: "Văn Xú", target: "Viên Thiệu", "type": "ally" },
  { source: "Văn Xú", target: "Quan Vũ", "type": "enemy" },
  { source: "Hứa Du", target: "Viên Thiệu", "type": "ally" },
  { source: "Hứa Du", target: "Tào Tháo", "type": "ally" },
  { source: "Trương Lỗ", target: "Lưu Bị", "type": "interact" },
  { source: "Mạnh Hoạch", target: "Chúc Dung", "type": "spouse" },
  { source: "Mạnh Hoạch", target: "Gia Cát Lượng", "type": "enemy" },
  { source: "Chúc Dung", target: "Mạnh Hoạch", "type": "spouse" },
  { source: "Chúc Dung", target: "Gia Cát Lượng", "type": "enemy" },
  { source: "Công Tôn Toản", target: "Lưu Bị", "type": "ally" },
  { source: "Công Tôn Toản", target: "Viên Thiệu", "type": "enemy" },
  { source: "Đào Khiêm", target: "Lưu Bị", "type": "interact" },
  { source: "Đào Khiêm", target: "Từ Thứ", "type": "interact" },
  { source: "Lưu Biểu", target: "Lưu Kỳ", "type": "parent" },
  { source: "Lưu Biểu", target: "Lưu Tông", "type": "parent" },
  { source: "Lưu Biểu", target: "Lưu Bị", "type": "relative" },
  { source: "Lưu Biểu", target: "Thái Mạo", "type": "relative" },
  { source: "Hoàng Tổ", target: "Tôn Kiên", "type": "enemy" },
  { source: "Lưu Chương", target: "Lưu Bị", "type": "relative" },
  { source: "Lưu Chương", target: "Pháp Chính", "type": "interact" },
  { source: "Trương Tú", target: "Tào Tháo", "type": "ally" },
  { source: "Trương Tú", target: "Giả Hủ", "type": "ally" },
  { source: "Sái Mạo", target: "Lưu Biểu", "type": "relative" },
  { source: "Sái Mạo", target: "Tào Tháo", "type": "ally" },
  { source: "Hoa Đà", target: "Quan Vũ", "type": "medical" },
  { source: "Hoa Đà", target: "Tào Tháo", "type": "medical" },
  { source: "Vương Doãn", target: "Điêu Thuyền", "type": "adopted" },
  { source: "Vương Doãn", target: "Đổng Trác", "type": "enemy" },
  { source: "Trương Liêu", target: "Lữ Bố", "type": "ally" },
  { source: "Trương Liêu", target: "Tào Tháo", "type": "ally" },
  { source: "Tả Từ", target: "Tào Tháo", "type": "interact" },
  { source: "Vu Cát", target: "Tôn Sách", "type": "interact" },
  { source: "Thái Văn Cơ", target: "Tào Tháo", "type": "interact" },
  { source: "Khổng Dung", target: "Tào Tháo", "type": "enemy" },
  { source: "Mê Hành", target: "Lưu Biểu", "type": "interact" },
  { source: "Mê Hành", target: "Tào Tháo", "type": "interact" },

  // Giao điểm trận Xích Bích
  { source: "Trận Xích Bích", target: "Chu Du", type: "battle" }, // Chỉ huy
  { source: "Trận Xích Bích", target: "Gia Cát Lượng", type: "battle" }, // Tham gia liên minh
  { source: "Trận Xích Bích", target: "Hoàng Cái", type: "battle" }, // Khổ nhục kế
];

if (typeof module !== 'undefined') {
  module.exports = { nodes, links };
}

window.nodes = nodes;
window.links = links;
